server.port=8086

# write scraped jobs to this base directory
output.base-path=/path/to/my/directory

# log file (Spring Boot logging)
logging.file.path=/path/to/my/directory

# REED API key info
reed.api.key=
reed.api.base-url=https://www.reed.co.uk/api/1.0/search

# ADZUNA API key info
adzuna.api.base-url=http://api.adzuna.com/v1/api/jobs/gb/search/1
adzuna.api.app-id=
adzuna.api.app-key=