server.port=8086

# write scraped jobs to this base directory
output.base-path=/mnt/c/kmt/cvs/CV2026/scrapedJobs

# REED API key info
reed.api.key=a31a9cdf-6b76-40d0-b03b-64c4818fadb6
reed.api.base-url=https://www.reed.co.uk/api/1.0/search

# ADZUNA API key info
adzuna.api.base-url=http://api.adzuna.com/v1/api/jobs/gb/search/1
adzuna.api.app-id=456fcc29
adzuna.api.app-key=95cfb096d6e8a3ea3e8fa3aace6e0686